#Nombre del workflow
name: Deploy to GitHub Pages

# Evento que Dispara la Ejecución. Este workflow se activará automáticamente cuando se suba (push) código a la rama principal (main).
on:
  push:
    branches:
      - main

jobs:
  # Nombre del Job
  build:
    name:
      Build Docusaurus
      # Máquina virtual que usará GitHub para ejecutar el trabajo.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4
        #Trae todo el código fuente del repositorio.
        with:
          #Asegura obtener todo el historial (necesario si Docusaurus usa metadatos de Git).
          fetch-depth: 0

      #Instala el gestor de paquetes alternativo pnpm (más rápido que npm).
      #- name: Install pnpm
      # uses: pnpm/action-setup@v4
      #  with:
      #  version: 10
      #   run_install: false

      #Configurar Node.js (Ambiente necesario para ejecutar Docusaurus)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    #Asegura que este Job solo se ejecute si el Job build finalizó con éxito.
    needs: build

    #Otorgua a GITHUB_TOKEN los permisos necesarios para realizar una implementación de páginas.
    permissions:
      pages: write #Para implementar en páginas.
      id-token: write #Para verificar que la implementación se origina de una fuente apropiada.

    #Implementar en el entorno de github-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        #Nativo de GitHub. Descarga el artefacto subido en el Job build y lo despliega oficialmente al servicio de GitHub Pages.
        uses: actions/deploy-pages@v4
